# Generated by Django 2.2.3 on 2019-07-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='created_by',
            new_name='author',
        ),
    ]
