# Generated by Django 2.2.3 on 2019-07-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questioncomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioncomment',
            old_name='comment',
            new_name='question_comment',
        ),
    ]
