# Generated by Django 2.2.3 on 2019-07-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='answer_title',
        ),
    ]
