# Generated by Django 2.2.3 on 2019-07-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20190722_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answercomment',
            old_name='comment',
            new_name='answer_comment',
        ),
    ]
