# Generated by Django 2.2.3 on 2019-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20190723_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvote',
            name='vote',
            field=models.CharField(choices=[('upVote', 'upVote'), ('downVote', 'downVote')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
