# Generated by Django 2.2.3 on 2019-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20190723_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionvote',
            name='vote',
            field=models.CharField(choices=[('upVote', 'upVote'), ('downVote', 'downVote')], default='upVote', max_length=20),
        ),
    ]
