# Generated by Django 2.2.3 on 2019-07-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20190723_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionvote',
            old_name='voter',
            new_name='user',
        ),
    ]
